version: '3'

services:
  elgalu:
    image: elgalu/selenium
    command: echo 0
    restart: "no" # ensures it does not get recreated

  dosel:
    image: dosel/zalenium
    depends_on:
    - elgalu
    command: echo 0
    restart: "no" # ensures it does not get recreated

  zaleniumgrid:
    image: dosel/zalenium
    container_name: zalenium
    depends_on:
    - dosel
    hostname: myhost
    ports:
    - "4445:4445"
    #bedaiin nama servicenya klo ada docker-compose file yg mau di up
    #bedaiin port nya klo ada docker-compose file yg mau di up
    restart: unless-stopped
    tty: true
    command: ["start", "--desiredContainers", "5", "--maxDockerSeleniumContainers", "20","--sauceLabsEnabled","false","--screenWidth", "1920", "--screenHeight", "1080"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /Users/fdn-prasetyo/Documents/docker-volumes/grid-docker:/home/seluser/videos
    privileged: true
    networks:
      mynetwork:
        aliases:
        - chrome

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
    - zalenium
    ports:
    - 8082:8082
    tty: true
    environment:
    - MOCK_SERVER_PORT=8082

networks:
  mynetwork:
    driver: bridge